#!/usr/bin/env python3.4
# -*- mode: python; indent-tabs-mode: nil -*-

import logging
import mlat.main

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO,
                        style='{',
                        format='{asctime}.{msecs:03.0f}  {levelname:8s} {name:20s} {message}',
                        datefmt='%Y%m%d %H:%M:%S')

    mlat.main.MlatServer().run()
